"""add date_analyse to articles_analyses

Revision ID: b13493bf345a
Revises: 5bb52f8e52e0
Create Date: 2025-04-29 21:54:12.230262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b13493bf345a'
down_revision: Union[str, None] = '5bb52f8e52e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles_analyses', sa.Column('date_analyse', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles_analyses', 'date_analyse')
    # ### end Alembic commands ###
